
public class Series extends Thread{
	String s;
	Series(String s)
	{
		this.s=s;
	}
	public void run()
	{
		for (int i = 1; i <= 10; i++)
		{
			System.out.println("i = "+i+" generated by --> "+s);
			try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	public static void main(String[] args) throws Exception {
		Series s1=new Series("John");
		Series s2=new Series("Doe");
		s1.start();
		s1.join();
		s2.start();
	}
}
